### ISSUE TITLE
RTL Control Directives not working

### ISSUE THREAD

**Issue by bdthemes** [MohammadYounes/grunt-rtlcss#5]
I try to add ignore Control Directives but it's not working like your online version. 

for example: 

```
.owl-carousel.owl-rtl{direction:rtl; /*rtl:ignore*/ } 
.owl-carousel.owl-rtl .owl-item{float:right; /*rtl:ignore*/} 
```

not working :(

**Comment by MohammadYounes** [comment]
You misplaced the directive. 

> The documentation states 
> * [Control directives](http://rtlcss.com/learn/usage-guide/control-directives/)  are placed between declarations or statements (rules and at-rules). They can target a single node (self-closing) or a set of nodes (block-syntax).
> * [Value directives](http://rtlcss.com/learn/usage-guide/value-directives/) are placed any where inside the declaration value. They target the containing declaration node.

To ignore the declaration:

```css
.owl-carousel.owl-rtl{direction:rtl/*rtl:ignore*/; } 
/* OR */
.owl-carousel.owl-rtl{/*rtl:ignore*/direction:rtl; } 
``` 

To ignore the entire selector:
```css
/*rtl:ignore*/ .owl-carousel.owl-rtl{direction:rtl;} 
```

To ignore the whole block :
```css
/*rtl:begin:ignore*/
.owl-carousel.owl-rtl{direction:rtl; } 
.owl-carousel.owl-rtl .owl-item{float:right;} 
/*rtl:end:ignore*/
```
Thanks.
